#!/bin/bash
# Regenerate docs/box-inventory.md from the live boxes.
#
# WHY THIS EXISTS: docs/box-inventory.md goes stale the moment anything is
# deployed, and a stale inventory is worse than none — it is trusted. This
# script is the answer to "is that still true?": re-run it rather than reading
# the doc and hoping. CLAUDE.md's service tables have drifted three times in a
# week; that is the failure this is meant to stop repeating.
#
#   ./scripts/inventory-boxes.sh > docs/box-inventory.md
#
# Read-only. Runs a handful of commands per box in ONE ssh session each,
# deliberately — CLAUDE.md warns against rapid repeated commands on prod.
set -uo pipefail

SYD="${SYD_HOST:-149.118.69.221}"
MEL="${MEL_HOST:-158.179.17.233}"

# Melbourne's docker needs sudo (nick is not in the docker group there) and,
# on Docker 29 with the containerd image store, its images live in
# /var/lib/containerd — NOT /var/lib/docker. Getting that wrong understates
# disk by ~5x, which is how a "green field" reading happened once already.
probe() {  # $1=host  $2=docker prefix ("" or "sudo")
  local h="$1" d="${2:-}"
  # shellcheck disable=SC2029  # $d is ours, deliberate expansion
  ssh -o ConnectTimeout=60 "$h" "
    echo '###HOST'; echo \"\$(nproc) vCPU | \$(free -g | awk '/Mem:/{print \$2}')GB RAM\"
    free -m | awk '/Mem:/{printf \"mem_used=%sMi mem_total=%sMi mem_avail=%sMi\n\", \$3, \$2, \$7}'
    df -h / | awk 'NR==2{printf \"disk_used=%s disk_total=%s disk_free=%s pct=%s\n\", \$3, \$2, \$4, \$5}'
    echo '###CONTAINERS'; $d docker ps --format '{{.Names}}|{{.Image}}|{{.Status}}' 2>/dev/null | sort
    echo '###MEM'; $d docker stats --no-stream --format '{{.Name}}|{{.MemUsage}}|{{.MemPerc}}' 2>/dev/null
    echo '###DF'; $d docker system df 2>/dev/null
    echo '###DOCKERDIRS'
    for p in /var/lib/docker /var/lib/containerd; do
      printf '  %-22s %s\n' \"\$p\" \"\$(sudo du -sh \$p 2>/dev/null | cut -f1)\"
    done
    echo '###UNITS'
    ls /etc/systemd/system/*.service /etc/systemd/system/*.timer 2>/dev/null | xargs -n1 basename \
      | grep -vE '^(dbus-org|snap\.|ip6?tables|iscsi|syslog|vmtoolsd)' | sort
    echo '###HOME'; sudo du -sh /home/* 2>/dev/null | sort -rh
  " 2>&1
}

echo "# Box inventory"
echo
echo "Generated by \`scripts/inventory-boxes.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
echo "**Re-run it rather than trusting these numbers** — see the header of that script."
echo
echo "## Sydney — $SYD (imagineering)"; echo; echo '```'; probe "$SYD" "";      echo '```'
echo "## Melbourne — $MEL (enspyr)";    echo; echo '```'; probe "$MEL" "sudo";  echo '```'
